### ISSUE TITLE
Allow dragging widgets to reorder

### ISSUE THREAD

**Issue by emibcn** [emibcn/covid#13] opened 2020-10-08 12:44 UTC
Add dragging capability to widgets.

Features:
- Consider unique line order (current) or multiple row/columns.
- Consider adding a `resize` function, to allow widgets with different sizes.
- On drag end: re-order widgets in URL hash and localStorage, or add a `position` property to each widget and handle it on add/remove/re-order.
- I have done something similar using [Dragact](https://github.com/Foveluy/Dragact). Might be useful here, or maybe we can use Material/UI own draggable, or something else.
- Drag handle: Use widget' title (like current app dialogs on non-small devices) or dedicated handle on it, like GitHub profile:
![image](https://user-images.githubusercontent.com/693791/95459256-b22b4000-0973-11eb-85e1-adf41c831006.png)

This should go into a new component (or multiple components wrapped up into just one), used in [`Widget/List`](https://github.com/emibcn/covid/blob/master/app/src/Widget/List.jsx#L287) to wrap the list of widgets.

**Comment by mblaul** [comment] 2020-10-09 23:03
I think I can handle this one!
I'll see what Material-UI has to offer first and if it's not great I'll look for another package.

**Comment by emibcn** [comment] 2020-10-10 08:36
@mblaul Assigned! If you need help or you think it's better to split the issue (for example: drag and resize), just ask for it ;)
Also, if in doubt about implementation design (for example, saving data, spliting components, renaming files, etc).

**Comment by mblaul** [comment] 2020-10-12 22:01
@emibcn Thanks! I think I'm going to go with [react-dnd](https://github.com/react-dnd/react-dnd/). I'll try refactoring some components to functional components to make use of react-dnd's hooks. They have a class API but it's marked as legacy.

**Comment by emibcn** [comment] 2020-10-13 10:59
Looks good!

**Comment by mblaul** [comment] 2020-10-24 01:48
Hey @emibcn! Just wanted to give an update so this issue doesn't go stale.

I haven't had a lot of time to work on this recently but I've got the basic drag-n-drop working for the cards.
I still need to work out the position tracking and URL update but I feel like I've made some decent progress:
![covid-dnd](https://user-images.githubusercontent.com/32026169/97065109-3fc47d80-1579-11eb-8b23-9b37a49b64cd.gif)

I also went with [react-sortable-hoc](https://github.com/clauderic/react-sortable-hoc) because it has the best support for grid layouts and touch devices.

I'll have some more free time soon so hopefully, I'll have this finished up by the end of the week.

**Comment by emibcn** [comment] 2020-10-24 13:00
Nice! For the order stuff, look at the widgets UUID list, which needs to be reordered with something like:
```javascript
onOrder = (id, newPosition) => {
   // Find current position (I don't know if is needed)
   const from = this.widgetsIds.findIndex(wID => wId === id);

   // Reorder ID
   this.widgetsIds.splice(fromIndex, 1);
   this.widgetsIds.splice(newPosition, 0, id);

   // Reorder data
   const widget = this.props.widgets[from];
   const widgets = this.props.widgets.filter(w => w.id !== id);
   widgets.splice(newPosition, 0, widget);

   // Save data
   return this.props.onChangeData({ widgets });
}
```

**Comment by emibcn** [comment] 2020-11-14 12:18
Hello @mblaul ! Any news on that? Do you need any help?

**Comment by mblaul** [comment] 2020-11-16 13:16
Hi @emibcn! I've made some good progress,   sorry for the lack of updates. I ran into some bugs with the data playback after my changes.

I'm going to try finishing this by Wednesday night my time (US EST). If I'm not done by then I'll push up everything I have to my fork and we can figure out what to do from there.

Thanks for checking in!

**Comment by emibcn** [comment] 2020-11-16 14:02
Great!! Thanks for the update!

**Comment by mblaul** [comment] 2020-11-18 01:52
@emibcn PR open here: https://github.com/emibcn/covid/pull/45

**Closed** 2020-11-19 07:44 UTC
Labels: Hacktoberfest, design, enhancement, javascript, react, ui/ux

**Comment by emibcn** [comment] 2020-11-22 19:02
### FYI:

Fixed issue caused by merging this without testing enough (my fault). The bug is widgets are not shown properly after saving reorder (some props move, others don't).

The problem was `IDs` also needed to be reordered (`this.widgetsIds` in `Widget/List` component).

https://github.com/emibcn/covid/commit/f6447a881cfee8878a7adc51aaac0e469bade17b

**Comment by mblaul** [comment] 2020-11-24 01:39
Sorry about that! Hope it wasn't too difficult to debug. I'll keep that in mind if I pick up another issue.

Thank you for linking to the fix and explaining the cause and solution!
